vi:
	vim \
		Makefile \
		gaze_pyside_app.py \
		calibration.py \
		settings.py \
		camsettingsh264.py \
		filters.py \
		mouse_control.py \
		util/list-cams \

do_anyway:
	echo "Generating tags"

tags: do_anyway
	ctags \
		gaze_pyside_app.py \
		calibration.py \
		settings.py \
		camsettingsh264.py \
		filters.py \
		mouse_control.py \

# Leave blank line above
